[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
buildbear = "https://rpc.buildbear.io/atomic-spiderman-b5abcdd1"
[etherscan]
buildbear = { key = "verifyContract", url="https://rpc.buildbear.io/verify/etherscan/atomic-spiderman-b5abcdd1" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
